version: "3.9"

services:
  backend:
    build: .
    restart: unless-stopped
    container_name: django_api
    command: bash -c "chmod +x /code/docker-entry-point.sh && /code/docker-entry-point.sh"
    ports:
      - "8080:8080"
    environment:
      - DJANGO_ENV=production
      - DJANGO_DATABASE_HOST=172.17.0.1
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
