openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/cargoes/:
    get:
      operationId: listCargos
      description: Retrieves a list of Cargo instances with optional filters.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CargoList'
          description: ''
      tags:
      - api
    post:
      operationId: createCargo
      description: 'Provides create functionality for Cargo instances.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CargoCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CargoCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CargoCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CargoCreate'
          description: ''
      tags:
      - api
  /api/cargoes/{id}/:
    get:
      operationId: retrieveCargo
      description: 'Provides retrieve functionality for Cargo instances.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this cargo.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CargoDetail'
          description: ''
      tags:
      - api
    put:
      operationId: updateCargo
      description: 'Provides update functionality for Cargo instances.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this cargo.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CargoEdit'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CargoEdit'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CargoEdit'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CargoEdit'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCargo
      description: 'Provides update functionality for Cargo instances.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this cargo.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CargoCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CargoCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CargoCreate'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CargoCreate'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCargo
      description: 'Provides delete functionality for Cargo instances.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this cargo.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/cars/{id}/:
    put:
      operationId: updateCar
      description: 'Provides the ability to update a Car location.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this car.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Car'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCar
      description: 'Provides the ability to update a Car location.'
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this car.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Car'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
          description: ''
      tags:
      - api
components:
  schemas:
    CargoList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        pick_up_location:
          type: string
        delivery_location:
          type: string
        nearest_cars_number:
          type: string
          readOnly: true
      required:
      - pick_up_location
      - delivery_location
    CargoDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        pick_up_location:
          type: string
        delivery_location:
          type: string
        weight:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000
          minimum: 1
        description:
          type: string
        cars:
          type: string
          readOnly: true
      required:
      - pick_up_location
      - delivery_location
      - weight
      - description
    CargoCreate:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        weight:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000
          minimum: 1
        description:
          type: string
        pick_up_location:
          type: string
        delivery_location:
          type: string
      required:
      - weight
      - description
      - pick_up_location
      - delivery_location
    Car:
      type: object
      properties:
        current_location:
          type: string
      required:
      - current_location
    CargoEdit:
      type: object
      properties:
        weight:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000
          minimum: 1
        description:
          type: string
      required:
      - weight
      - description
